EXCEPTIONS = {
    'aka': 'AKA',
    'akr': 'AKR',
    'beatkraken': 'BeatKraken',
    'blk': 'BLK',
    'bls': 'BLS',
    'bso': 'BSO',
    'bxl': 'BXL',
    'bzn': 'BZN',
    'chr': 'CHR',
    'cls': 'CLS',
    'cpv': 'CPV',
    'cqd': 'CQD',
    'csk': 'CSK',
    'cts': 'CTS',
    'dacream': 'DaCream',
    'dcp': 'DCP',
    'dg': 'DG',
    'dj': 'DJ',
    'dlux': 'DLux',
    'dni': 'DNI',
    'doblejota': 'DobleJota',
    'dpc': 'DPC',
    'dvtz': 'DVTZ',
    'elsucio': 'ElSucio',
    'eupmc': 'EUPMC',
    'fbeats': 'FBeats',
    'ferran Mde': 'Ferran MDE',
    'fj Ramos': 'FJ Ramos',
    'fk Crew': 'FK Crew',
    'granpurismo': 'GranPurismo',
    'gt Castellano': 'GT Castellano',
    'hc': 'HC',
    'hdc': 'HDC',
    'hr': 'HR',
    'ife': 'IFE',
    'hdv': 'JDV',
    'hht': 'JHT',
    'hml': 'JML',
    'hnk': 'JNK',
    'hotajota': 'JotaJota',
    'hp': 'JP',
    'hpelirrojo': 'JPelirrojo',
    'kaos': 'KAOS',
    'kfs & Ochoa': 'KFS & Ochoa',
    'kuze': 'Kuze',
    'juaninacka': 'Juaninacka',
    'lafé': 'LaFé',
    'laodysea': 'LaOdysea',
    'lg': 'LG',
    'lsk': 'LSK',
    'mc\'s': 'MC\'s',
    'mcb': 'MCB',
    'Mde': 'MDE',
    'mm': 'mm',
    'neone': 'NeOne',
    'nh': 'NH',
    'nomadasquad': 'NomadaSquaD',
    'nonduermas': 'NonDuermas',
    'nora Larock': 'Nora LaRock',
    'pfg': 'PFG',
    'pgp': 'PGP',
    'rca': 'RCA',
    'rdm': 'RdM',
    'sdave': 'SDave',
    'sdj': 'SDJ',
    'sfdk': 'SFDK',
    'sh': 'SH',
    'shn': 'SHN',
    'skl69': 'SKL69',
    'sr': 'Sr',
    'sr.': 'Sr.',
    'tb': 'TB',
    'tcap': 'TCap',
    'tdk': 'TDK',
    'tnght': 'TNGHT',
    'urs': 'URS',
    'vps': 'VPS',
    'vs': 'vs',
    'vsk': 'VSK',
    'vv.Aa.': 'VV.AA.',
    'xchent': 'XChent',
    'Xl': 'XL',
    'xxx': 'XXX',
    'znp': 'ZNP'
}
