EXCEPTIONS = {
    'Beatkraken': 'BeatKraken',
    'Blk': 'BLK',
    'Bls': 'BLS',
    'Bzn': 'BZN',
    'Chr': 'CHR',
    'Cls': 'CLS',
    'Cpv': 'CPV',
    'Cqd': 'CQD',
    'Dacream': 'DaCream',
    'Dcp': 'DCP',
    'Dg': 'DG',
    'Dj': 'DJ',
    'Dlux': 'DLux',
    'Dni': 'DNI',
    'Doblejota': 'DobleJota',
    'Dpc': 'DPC',
    'Dvtz': 'DVTZ',
    'Elsucio': 'ElSucio',
    'Eupmc': 'EUPMC',
    'Fbeats': 'FBeats',
    'Ferran Mde': 'Ferran MDE',
    'Fj Ramos': 'FJ Ramos',
    'Fk Crew': 'FK Crew',
    'Granpurismo': 'GranPurismo',
    'Gt Castellano': 'GT Castellano',
    'Hc': 'HC',
    'Hdc': 'HDC',
    'Hr': 'HR',
    'Ife': 'IFE',
    'Jht': 'JHT',
    'Jml': 'JML',
    'Jnk': 'JNK',
    'Jotajota': 'JotaJota',
    'Jp': 'JP',
    'Jpelirrojo': 'JPelirrojo',
    'Kaos': 'KAOS',
    'Kfs & Ochoa': 'KFS & Ochoa',
    'Lafé': 'LaFé',
    'Laodysea': 'LaOdysea',
    'Lg': 'LG',
    'Lsk': 'LSK',
    'Mcb': 'MCB',
    'Mde': 'MDE',
    'Neone': 'NeOne',
    'Nh': 'NH',
    'Nomadasquad': 'NomadaSquaD',
    'Nonduermas': 'NonDuermas',
    'Nora Larock': 'Nora LaRock',
    'Pfg': 'PFG',
    'Pgp': 'PGP',
    'Rca': 'RCA',
    'Rdm': 'RdM',
    'Sdave': 'SDave',
    'Sdj': 'SDJ',
    'Sfdk': 'SFDK',
    'Sh': 'SH',
    'Shn': 'SHN',
    'Skl69': 'SKL69',
    'Sr': 'Sr',
    'Sr.': 'Sr.',
    'Tcap': 'TCap',
    'Tdk': 'TDK',
    'Tnght': 'TNGHT',
    'Urs': 'URS',
    'Vps': 'VPS',
    'Vs': 'vs',
    'Vsk': 'VSK',
    'Vv.Aa.': 'VV.AA.',
    'Xchent': 'XChent',
    'Xl': 'XL',
    'Xxx': 'XXX',
    'Znp': 'ZNP'
}
