EXCEPTIONS = {
    'Bboy': 'BBoy',
    'Bcm': 'BCM',
    'Cd': 'CD',
    'Dvd': 'DVD',
    'Ep': 'EP',
    'Ii': 'II',
    'Ljda': 'LJDA',
    'Lp': 'LP',
    'Mc': 'MC',
    'Rne3': 'RNE3',
    'Sdave': 'SDave',
    'Tdk': 'TDK',
    'Thx': 'THX',
    'Tv': 'TV',
    'Xl': 'XL',
    'Xxl': 'XXL',
    'Xxx': 'XXX',
    'Vs': 'vs',
    'Yoseguiré': 'yOSEguiré'
}
